update-conf.d 2012-04-03: add help text when on command-line argument specified.

diff --git a/update-conf.d.in b/update-conf.d.in
--- a/update-conf.d.in
+++ b/update-conf.d.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Version 2011-10-26
+# Version 2012-04-03
 #
 # Script for flexible /etc/*.d configuration
 # Originally from Atha, with a lot of improvements from truc - thanks!
@@ -25,6 +25,8 @@
 
 
 ## SETUP
+# scriptname:
+scriptname=$(basename "$0")
 # root of configuration files:
 root="@CONFIGDIR@"
 # script configuration path:
@@ -53,24 +55,40 @@ message () {
 
 ## MAIN PROGRAM
 if [ ! -f "${scriptconf}" ]; then
-        echo "Script configuration file '${scriptconf}' not found!" >&2
-        exit 1
+  echo "${scriptname}: Script configuration file '${scriptconf}' not found!" >&2
+  exit 1
+fi
+
+if [ $# -lt 1 ]; then
+  echo "${scriptname}: <conf> entry must be specified as a command-line argument.
+${scriptname}: type \"${scriptname} ?\" for a list of valid <conf> entries." >&2
+  exit 1
+fi
+
+if [ "${conf}" = "?" ]; then
+  echo "Usage: ${scriptname} <conf>
+
+List of valid <conf> entries:"
+  cat ${scriptconf}
+  echo "
+Edit ${scriptconf} to add or delete entries."
+  exit 0
 fi
 
 if ! grep "^${conf}$" "${scriptconf}"; then
-        echo "Not allowed to process file ${confpath}, see ${scriptconf}." >&2
-        exit 1
+  echo "${scriptname}: Not allowed to process file ${confpath}, see ${scriptconf}." >&2
+  exit 1
 fi
 
 if [ ! -d "${dpath}" ] ; then
-  echo "${0}: ${dpath} is not present!" >&2
+  echo "${scriptname}: ${dpath} is not present!" >&2
   exit 1
 fi
 
 if [ -e "${dconfpath}" ] ; then
-  echo "${0}: please remove ${dconfpath} before you run this script.
-${0}: NOTE: It may have been left by a previously run ${0}, but you should check anyway." >&2
-  exit 1
+  echo "${scriptname}: please remove ${dconfpath} before you run this script.
+${scriptname}: NOTE: It may have been left by a previous run, but you should check anyway." >&2
+  exit 2
 fi
 
 cat << 'EOT' > "${dconfpath}" && message "${dconfpath} created, header added"
@@ -93,4 +111,5 @@ done
 mv -f "${confpath}" "${bkpconfpath}" && message "Existing ${confpath} renamed to ${bkpconfpath}"
 mv -f "${dconfpath}" "${confpath}" && message "New configuration file ${dconfpath} moved to ${confpath}"
 
+echo "${scriptname}: ${confpath} updated."
 exit 0
